<div class="row">
				<div class="col-lg-12">
					<div class="panel panel-default">
						<div class="panel-heading clearfix">
							<h3 class="panel-title">Импорт</h3>							
						</div>
						<div class="panel-body">
							<div id="rootwizard" class="form-horizontal form-wizard">
								<div class="wizard-navbar">
									<ul><!-- class="completed"-->
										<?
											$steps=array(
												'#tab1'=>'Загрузка файла импорта',
												'#tab2'=>'Предпросмотр',
												'#tab3'=>'Отчет',
												
												);
											$i=1;
											echo '<!--'.$this->step.'-->';
											foreach($steps as $name=>$row)
											{
												echo '<li'.($name==('#tab'.$this->step)?' class="active"':'').'><a href="'.$name.'" data-toggle="tab"><span>'.($i++).'</span> '.$row.'</a></li>';
											}
										?>
										
									</ul>
								</div>
								<div class="tab-content">
									<div class="tab-pane <? echo ($this->step==1?'active':'');?>" id="tab1">									
										Формат файла CSV, колонки:
										<ul><li>Номер квартиры<li>RFID номер ключа 1<li>RFID номер ключа 2<li>RFID номер ключа N</ul>
										<form action="<? echo BASE_PATH; ?>clients/import/" method="post" enctype="multipart/form-data">
											  
											  <div class="form-group">
												<label for="intercoms">Номера домофонов через запятую</label>
												<input type="text" name="intercoms" class="form-control" id="intercoms">
											  </div>											  <div class="form-group">
												<label for="file_import">Файл импорта</label>
												<input type="file" name="importfile" class="form-control" id="file_import">
											  </div>											  
											  <button type="submit" class="btn btn-primary">Загрузить</button>
										</form>
									</div>
									<div class="tab-pane <? echo ($this->step==2?'active':'');?>" id="tab2">	
										<div class="table-responsive">
											
												<? 
												/*if($this->rows)
												{
													echo '<table class="table table-bordered">
												<thead> 
													<tr> 
														<th>№</th> 
														<th>Номер домофона</th> 
														<th>Часовойпояс</th> 
														<th>Город</th> 
														<th>Улица</th> 
														<th>Номер дома</th> 
														<th>Номерквартиры</th> 
														<th>Телефон</th> 
														<th>E-mail</th> 
														<th>Гостевой код</th> 
														<th title="окончания действия гостевого кода">Дата </th> 
														<th>RFID ключи</th> 
														<th>SIP-аккаунты</th> 
														<th>Коды</th> 
														<th>Телефоны</th> 
													</tr> 
												</thead> 
												<tbody> ';
												$i=1;
												foreach($this->rows as $row)
												{
													echo '<tr>
														<th scope="row">'.($i++).'</th> ';
													foreach($row as $col)echo '<td>'.$col.'</td>';
													echo '</tr>';													
												}
												
										echo '</tbody> 
											</table>';	
												}*/											
												if($this->step==2 and $this->rows)
												{
													echo '<table class="table table-bordered">
												<thead> 
													<tr> 
														<th>№ квартиры</th> 
														<th>Номер домофона</th> 
														<th>Клиент</th> 
														<th>RFID ключи</th> 
													</tr> 
												</thead> 
												<tbody> ';
												foreach($this->rows as $row)
												{
													echo '<tr>';
													echo '<td>'.$row['flat'].'</td>';
													
													echo '<td>'.implode(',',$this->intercoms).'</td>';
													echo '<td>';
													if(!empty($row['client']))
													{
														echo $row['client']['fio'];
													}else echo 'Новый клиент';
													echo '</td>';
													if(!empty($row['keys']))echo '<td>'.implode(',',$row['keys']).'</td>';
													echo '</tr>';													
												}
												
												echo '<tbody></table>';
												echo '<form method="post">
												<input type="hidden" name="import_session" value="'.$this->import_session.'">
												<input type="hidden" name="flush" value="1">
												<button type="submit" class="btn btn-primary">Импортировать ключи и создать клиентов</button> ('.count($this->rows).')</form>';
												}
												
												?>	
												
										</div>
										
									</div>
									<div class="tab-pane <? echo ($this->step==3?'active':'');?>" id="tab3">	
										<div class="table-responsive" id="activate_table">
											
											<?php
											if($this->step==3)
											{
												echo '<h2>Коды активации домофонов:'.implode(', ',$this->intercoms).'</h2>';
												echo '<table class="table table-bordered">
												<thead> 
													<tr> 
														<th>№ квартиры</th> 
														<th>Код активации</th> 
													</tr> 
												</thead> 
												<tbody> ';
												foreach($this->rows as $row)
												{
													echo '<tr>';
													echo '<td>'.$row['flat'].'</td>';
													echo '<td>'.$row['clientCode'].'</td>';
													echo '</tr>';													
												}												
												echo '<tbody></table>';
											}
											?>
										</div>
									</div>
									<!--<ul class="pager wizard"> 
										<li class="previous first"><a href="javascript:void(0)">В начало</a></li> 
										<li class="previous"><a href="javascript:void(0)"><i class="icon-left-open"></i>Предыдыщий</a></li> 
										<!--<li class="next last"><a href="javascript:void(0)">Последний</a> </li> 
										<li class="next"><a href="javascript:void(0)">Следующий <i class="icon-right-open"></i></a> </li> 
									</ul>-->
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
