<?
#print_r($this->session);
?>
		<div class="row datatable-wrapper form-inline">
			<div class="col-lg-12">
				<div class="data-col-first clearfix">
					<form method="post" action="<? echo BASE_PATH.'clients/group/'; ?>" class="group_action">
					<div class="col-checkbox col-space">
						<div class="form-checkbox" title="выбрать все">
							<input type="checkbox" class="select_all"  value="1" name="all"> <span class="check"><i class="fa fa-check"></i></span>
						</div>
					</div>
					
					<div class="col-selectbox">
						<select class="form-control input-sm" name="action">
							<option value="">с выбранными</option>
							<option value="block">заблокировать</option>
							<option value="activate">разблокировать</option>
							<option value="print">напечатать коды активации</option>
							<option value="bill">выставить счет</option>
							<option value="send_message">отправить сообщение</option>
							<!--<option value="voting">провести голосование</option>Добавил Игорь!-->
							<option value="delete">удалить</option>
							<!--<option value="change">изменить данные</option>-->
						</select>&nbsp;
						<input type="hidden" value="" name="ids">
						<button class="btn btn-primary btn-sm" type="submit">Применить</button>
					</div>
					</form>
				</div>
				<div class="data-col-last clearfix">
				<button class="btn btn-sm btn-success btn-outline filter_show" type="button" ><i class="fa fa-filter"></i> Фильтровать список</button>
				</div>
				<!--<div class="data-col-last clearfix">
					<div class="col-selectbox">
						<select class="form-control input-sm">
							<option>Сортировать по</option>
							<option>ФИО</option>
						</select>
					</div>
					<div class="col-selectbox">
						<select class="form-control input-sm">
							<option>25 Records</option>
							<option>10 Records</option>
							<option>50 Records</option>
						</select>
					</div>
				</div>-->
			</div>
		</div>	
		<div class="row group_bill" style="display:none;">
			<div class="col-lg-7">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title">Выставление счета</h3>
						<ul class="panel-tool-options"> 
							<li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>							
							<li><a data-rel="close" href="#"><i class="icon-cancel"></i></a></li>
						</ul>
					</div>
					<div class="panel-body">				
						<form method="post" class="form-horizontal" action="<? echo BASE_PATH.'bills/'; ?>">
							<input type="hidden" name="action" value="change_group">
							<input type="hidden" value="" name="ids">
						 	<div class="form-group"> 
								<label class="col-sm-2 control-label">Месяц</label> 
								<div class="col-sm-10"> 
								<select name="month" class="form-control">
									<option value="1">Январь</option>	
								</select>
								</div> 
							</div>
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Год</label> 
								<div class="col-sm-10"> 
								<select name="year" class="form-control">
												<option value="2017">2017</option>	
								</select>
								</div> 
							</div>
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Сумма</label> 
								<div class="col-sm-10"> 
									<input type="summ" placeholder="0000" name="summ" class="form-control"> 
								</div> 
							</div>
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Комментарий</label> 
								<div class="col-sm-10"> 
									<input type="comment" placeholder="например: оплаза за Январь 2017" name="comment" class="form-control"> 
								</div> 
							</div>
							
							<div class="line-dashed"></div>
							<div class="form-group"> 
								<div class="col-sm-offset-2 col-sm-10"> 
									<button class="btn btn-primary" type="submit">Выставить счет</button> 
									<span class="help-block m-b-none count_items"></span>									
								</div> 
							</div>	
						</form>	
					</div>		
				</div>		
			</div>
		</div>
		
		<div class="row group_change" style="display:none;">
		<div class="col-lg-7">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title">Обновление данных выбранных клиентов</h3>
						<ul class="panel-tool-options"> 
							<li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>							
							<li><a data-rel="close" href="#"><i class="icon-cancel"></i></a></li>
						</ul>
					</div>
					<div class="panel-body">				
						<form method="post" class="form-horizontal" action="<? echo BASE_PATH.'clients/group/'; ?>">
							<input type="hidden" name="action" value="change_group">
							<input type="hidden" value="" name="ids">
						 	<div class="form-group"> 
								<label class="col-sm-2 control-label">Фамилия</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="last_name_checked"></span>
									<input type="text" placeholder="Фамилия" name="last_name"  class="form-control"> 
								</div> 
							</div>
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Имя</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="first_name_checked"></span>
									<input type="text" placeholder="Имя" name="first_name"  class="form-control"> 
								</div> 
							</div>
							
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Отчество</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="father_name_checked"></span>
									<input type="text" placeholder="Отчество" name="father_name"  class="form-control"> 
								</div> 
							</div>							
							<div class="form-group"> 
								<div class="col-sm-offset-2 col-sm-10"> 
									<div class="checkbox">
										 <label> <input type="checkbox" value="1" name="act" value="1"> Включен</label> 
									</div> 
								</div> 
							</div>		
							<div class="line-dashed"></div>
							
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Номер телефона</label> 
								<div class="col-sm-10 input-group"> 
								<span class="input-group-addon"><input type="checkbox" value="1" name="phone_checked"></span>									
										<span class="input-group-addon">+7</span> 
										<input type="text" placeholder="(999) 999-9999" data-mask="(999) 999-9999" name="phone"  class="form-control"> 
									
								</div> 
							</div>
							
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Электронная почта</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="email_checked"></span>
									<input type="text" placeholder="mail@example.ru" name="email"  class="form-control"> 
									</div>
									
							</div>							
							<!--
							<div class="line-dashed"></div>
													
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Город</label> 
								<div class="col-sm-10 input-group"> 								
									<span class="input-group-addon"><input type="checkbox" value="1" name="city_checked"></span>
									<select name="city" class="form-control">
									<option value="0">Не выбран</option>										
									<?
										foreach($this->cities as $city)
										{
											echo '<option value="'.$city['id'].'">'.$city['text'].'</option>';
										}
									
									?>
									</select>
									<span class="input-group-btn"><button class="btn btn-default add_city" type="button">добавить город</button></span>
									<input type="text" placeholder="Название города" name="city_new"  class="form-control" style="display:none;"> 
									<?
									/*if($this->cities){										
										echo '<script>var cities='.json_encode($this->cities).';</script>';
									}*/
									if($this->streets) echo '<script>var streets='.json_encode($this->streets).';</script>';
									?>
								</div> 
							</div>
							
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Улица</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="street_checked"></span>
									<input type="text" placeholder="Улица" name="street"  class="form-control"> 
								</div> 
							</div>
							
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Дом</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="bild_checked"></span>
									<input type="text" placeholder="Дом" name="bild"  class="form-control"> 
								</div> 
							</div>
							
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Корпус</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="korp_checked"></span>
									<input type="text" placeholder="Корпус" name="korp"  class="form-control"> 
								</div> 
							</div>
							
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Квартира</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="flat_checked"></span>
									<input type="text" placeholder="Квартира" name="flat"  class="form-control"> 
								</div> 
							</div>
							-->
														
							<div class="line-dashed"></div>
							
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Код</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="clientCode_checked"></span>
									<input type="text" placeholder="" name="clientCode"  class="form-control"> 
								</div> 
							</div>
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Домофон</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="domophone_checked"></span>
									<input type="text" placeholder="номер домофона" name="domophone"  class="form-control"> 
								</div> 
							</div>
							
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Гостевой код</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="guestCode_checked"></span>
									<input type="text" placeholder="" name="guestCode"  class="form-control"> 
								</div> 
							</div>
														
							<div class="form-group"> 
								<label class="col-sm-2 control-label">Временная зона</label> 
								<div class="col-sm-10 input-group"> 
									<span class="input-group-addon"><input type="checkbox" value="1" name="timezone_checked"></span>
									<input type="text" placeholder="" name="timezone"  class="form-control"> 
								</div> 
							</div>
							<div class="form-group"> 
								<div class="col-sm-offset-2 col-sm-10"> 
									<div class="radio"> <label> <input type="radio" value="checked" id="optionsradios1" name="replace" checked="checked">Заменить только отмеченные поля</label> </div> 
								 	<div class="radio"> <label> <input type="radio" value="all" id="optionsradios2" name="replace">Заменить все поля</label> </div>
								 </div>
							</div>
							
							<div class="line-dashed"></div>
							<div class="form-group"> 
								<div class="col-sm-offset-2 col-sm-10"> 
									<button class="btn btn-primary" type="submit">Применить</button> 
									<span class="help-block m-b-none count_items"></span>									
								</div> 
							</div>		
						</form>			
					</div>
				</div>
			</div>
</div>

		<div class="table-responsive">
			<table class="table table-users table-hover">
				<thead>
					<tr>
						<th class="size-60"></th>
						<th>ФИО</th>
						<th>Номер телефона</th>
						<th>Город</th>
						<th>Адрес</th>
						<th>Кв.</th>
						<th>Домофон</th>
						<th class="text-center">Сервисы</th>
						<th class="text-center">Статус</th>
						<th class="size-80" class="text-center">Действия</th>
					</tr>
				</thead>
				<tbody>
				<? if($this->rows)
					foreach($this->rows as $row)
					{
						echo '<tr>
						<td class="size-60"><div class="form-checkbox"><input type="checkbox" name="id[]" class="id_field" value="'.$row['id'].'"> <span class="check"><i class="fa fa-check"></i></span></div></td>
						<td><a href="'.BASE_PATH.'clients/edit/'.$row['id'].'">'.$row['fio'].'</a></td>
						<td>'.(empty($row['phone'])?'':'+7 '.$row['phone']).'</td>
						<td>'.$row['city'].'</td>
						<td>'.$row['addres'].'</td>
						<td>'.$row['flat'].'</td>
						<td>'.$row['intercom'].'</td>
						<td class="text-center">';
						foreach($row['services'] as $intercom)
						{
							foreach($intercom as $name=>$value)
								if($value==1)echo ' <span class="badge badge-bordered">'.$name.'</span>';
							echo '<br>';
						}
						echo '</td>
						<td align=center>';						
						if($row['act']=='1')
						//if($row['is_debt']=='0')
							echo '<a title="заблокировать" href="'.BASE_PATH.'clients/block/'.$row['id'].'"><i class="icon-check icon-larger green-color"></i></a>';
						else echo '<a  title="разблокировать" href="'.BASE_PATH.'clients/activate/'.$row['id'].'"><i class="icon-check icon-larger red-color"></i></a>';
						echo '</td><td class="size-80">
							<div class="dropdown">
								<a href="#/" data-toggle="dropdown" class="more-link"><i class="icon-dot-3 ellipsis-icon"></i></a>
								<ul class="dropdown-menu dropdown-menu-right">
								<li><a href="'.BASE_PATH.'clients/edit/'.$row['id'].'">Редактировать</a></li>
									';
						if($row['act']=='1')
						//if($row['is_debt']=='0')									
							echo '<li><a href="'.BASE_PATH.'clients/block/'.$row['id'].'">Заблокировать</a></li>'; 
						else echo '<li><a href="'.BASE_PATH.'clients/activate/'.$row['id'].'">Разблокировать</a></li>';
							echo '<li><a href="'.BASE_PATH.'clients/reset/'.$row['id'].'" class="confirm" confirm="Вы уверены что хотите сбросить пароль клиента '.$row['fio'].'?">Сбросить пароль</a></li>
								  <li><a href="'.BASE_PATH.'notify/add/'.$row['id'].'">Отправить сообщение</a></li>
								  <li><a href="'.BASE_PATH.'clients/delete/'.$row['id'].'" class="confirm" confirm="Вы уверены что хотите удалить клиента '.$row['fio'].'?">Удалить</a></li>								
								</ul>
							</div>
						</td>
					</tr>';
					}
				?>
				</tbody>
			</table>
			<?php
			if($this->count_all>$this->on_page)
			{
				if($this->paginator_add)
				{					
					$url_append='&filter=true&'.implode('&',$this->paginator_add);
				}
				else $url_append='';
				
				echo '<div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">
					<ul class="pagination">';
				if($this->page>1)	
						echo '<li class="paginate_button previous" id="DataTables_Table_0_previous"><a href="?page='.($this->page-1).$url_append.'" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0">Предыдущие</a></li>';
				for ($i = 0; $i <= round($this->count_all/$this->on_page); $i++)
				{
					echo '<li class="paginate_button'.($this->page==$i?' active':'').'"><a href="?page='.$i.$url_append.'" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0">'.($i+1).'</a></li>';
				}
				if($this->page<round($this->count_all/$this->on_page))
					echo '<li class="paginate_button next" id="DataTables_Table_0_next"><a href="?page='.($this->page+1).$url_append.'" aria-controls="DataTables_Table_0" data-dt-idx="7" tabindex="0">Следующие</a></li>';
				echo '</ul></div>';
			}

			?>

		</div>


