<?php
if($this->rows['status'] == '1'){
echo '<div class="ajax panel-body">
    <p><strong>Вам пришло сообщение</strong></p>
    <button type="button" class="demo btn btn-primary" data-toggle="modal" data-target="#modal-1">Прочитать сообщение</button>
</div>';
#echo $this->rows['status'];
}
?>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading clearfix">
				<h3 class="panel-title">
				<?php
				if($this->rows['notify']== 1)echo 'Не оплачен долг!';
				elseif($this->rows['notify']==2)echo 'Персональное сообщение';
                                elseif($this->rows['notify']==3)echo 'Общедомовое сообщение. '.$this->groupNotifyName;
				?></h3>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" method="post">
					<input type="hidden" name="id" value="<? echo $this->rows['id'] ?>">
					<input type="hidden" name="action" value="save">
					<input type="hidden" name="group_id" value="<? echo $this->rows['group_id'] ?>">
					<input type="hidden" name="client_id" value="<? echo $this->rows['client_id'] ?>">

					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<div class="checkbox">
								<label> <input type="checkbox" name="enter_all" value="1" <? echo ($this->rows['enter_all']=='1'?'checked':''); ?>> Не стандартное сообщение</label>
							</div>
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label">Извещение</label>
						<div class="col-sm-10">
							<div class="input-group">
								<select name="notify" class="form-control add_txt_notify"><option value="0">Сообщение не выбрано</option>
								<?
									$i=1;
									foreach($this->txt_notify as $t_notify)
									{
										echo '<option value="'.$i.'"'.($this->rows['notify']==$i?' selected':'').' >'.$t_notify.'</option>';
										$i++;
									}
								?>
								</select>
							</div>
						</div>
					</div>

					<div class="form-group search_new"> <!-- style="display:none;" -->
						<label class="col-sm-2 control-label">Текст сообщения</label>
						<div class="col-sm-10">
							<textarea name="notify_text" class="form-control"><? echo $this->notify_txt ?></textarea>
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label">Адресуется</label>
						<div class="col-sm-10">
							<input type="text" placeholder="" name="client" value="<? echo $this->rows['fio'] ?>" class="form-control">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label">Начало действия</label>
						<div class="col-sm-10">
							<input type="text" placeholder="" name="startTime" value="<? echo $this->rows['startTime'] ?>" class="form-control">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label">Окончание действия</label>
						<div class="col-sm-10">
							<input type="text" placeholder="" name="endTime" value="<? echo $this->rows['endTime'] ?>" class="form-control">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label">Домофон</label>
						<div class="col-sm-10">
							<input type="text" placeholder="" name="intercom" value="<? echo $this->rows['intercom'] ?>" class="form-control">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label">Статус</label>
						<div class="col-sm-10">
							<div class="checkbox">
								<label> <input type="checkbox" name="status" value="1" <?
								if($this->status) echo ('1'==$this->status ? 'checked' : '');
								else echo ($this->rows['status']=='1'?'checked':'');
							    ?>>Запустить доставку сообщения</label>
							</div>
						</div>
					</div>

					<div class="line-dashed"></div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<div class="checkbox">
								<label> <input type="checkbox" name="continue" value="1" <? echo (isset($_SESSION['continue_edit'])?'checked':''); ?>> продолжить редактирование </label>
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button class="btn btn-primary" type="submit">Сохранить</button> <button class="btn btn-small button_link" rel="<? echo BASE_PATH; ?>notify/list/" type="submit">Отменить</button>
						</div>
					</div>


				</form>
			</div>
		</div>
	</div>
</div>
<?php
if($this->rows['status'] == '1'){

echo '<div id="modal-1" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Новое сообщение</h4>
      </div>
      <div class="modal-body">
        <p>';
	            if($this->rows['notify']== 1)echo 'Не оплачен долг!';
                    elseif($this->rows['notify']==2)echo 'Персональное сообщение';
                    elseif($this->rows['notify']==3)echo 'Общедомовое сообщение. '.$this->groupNotifyName;
        	    echo "<br>".$this->notify_txt;
	echo '</p>
	<form class="modal-form">
	<input type="hidden" name="id" value="';
	echo $this->rows['id'];
	echo '">
	</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Прочитано</button>
      </div>
    </div>
  </div>
</div>';

}
?>