<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Анкета</h3>
</div>
<div class="modal-body">
  <form class="modal-form">
          <div class="form-group">
            <label for="recipient-name" class="control-label">Кому:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Сообщение:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
   </form>
</div>
<div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn">Закрыть</button>
    <button type="button" class="btn btn-primary btn-aut update">Оправить</button>
</div>