<?
if($this->pay_count!='' or !empty($_POST))echo '<h2>Принято оплат из файла: '.$this->pay_count.'</h2>';
?>
<div class="panel panel-default">
						<div class="panel-heading clearfix"> 
							<div class="panel-title">Выберите файл импорта платежей</div> 
							
						</div> 
						<!-- panel body --> 
						<div class="panel-body"> 
							<form action="<? echo BASE_PATH; ?>bills/gorodpays/" method="post" enctype="multipart/form-data">
							<div class="form-group">
									
									<input type="file" name="importfile" class="form-control" id="file_import">
							  </div>			  
											
							<button type="submit" class="btn btn-primary">Загрузить</button>
											  
							</form>
							
						</div> 
					</div> 
					
					