<?
//print_r($this->arr);
?>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading clearfix">
				<h3 class="panel-title">
				<?php
				echo "Новое собрание";
				?></h3>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" method="post">
					<input type="hidden" name="action" value="save">
					<input type="hidden" name="group_id" value="<? echo $this->rows['group_id'] ?>">
					<input type="hidden" name="ids" value="<? echo $this->ids ?>">

					<div class="form-group">
						<label class="col-sm-2 control-label">Тема собрания</label>
						<div class="col-sm-10">
							<input type="text" placeholder="" name="meeting" value="<? echo $this->rows['meeting'] ?>" class="form-control">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Вопросы голосования</label>
						<div class="col-sm-10">
							<div id="answer_tab">
								<?
								if($this->arr){
									foreach($this->arr as $key=>$value)
								        {
										explode(":",$value);
										echo "<div class=\"answer_line\">
							                        <input type=\"text\" name=\"questions[".$key."]\" value=\"".$value."\" class=\"form-control-answer\">
							                        <input type=\"hidden\" name=\"answer_del[".$key."]\" value=\"0\" class=\"remove\">
							                        <a href=\"#\" class=\"del\" title=\"удалить ответ\"><i class=\"fa fa-times\" aria-hidden=\"true\"></i></a>
							                        </div>";
									}
								}
								?>
							</div>
							<a href="#" data-rel="collapse"  id="plus_answer"><i class="fa fa-plus" aria-hidden="true"></i> Добавить вопрос</a>
						</div>
					</div>


					<div class="form-group">
						<label class="col-sm-2 control-label">Аудитория</label>
						<div class="col-sm-10">
							<input type="text" placeholder="" name="group_id" value="<? echo $this->rows['group_id'] ?>" class="form-control">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label">Дата сосздания</label>
						<div class="col-sm-10">
							<input type="text" placeholder="" name="data" value="<? echo $this->rows['data'] ?>" class="form-control">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label">Окончание действия</label>
						<div class="col-sm-10">
							<input type="text" placeholder="" name="endTime" value="<? echo $this->rows['endTime'] ?>" class="form-control">
						</div>
					</div>


					<div class="form-group">
						<label class="col-sm-2 control-label">Статус</label>
						<div class="col-sm-10">
							<div class="checkbox">
								<label> <input type="checkbox" name="status" value="1" <?
								if($this->status) echo ('1'==$this->status ? 'checked' : '');
								else echo ($this->rows['status']=='1'?'checked':'');
							    ?>>Открыть собрание</label>
							</div>
						</div>
					</div>

					<div class="line-dashed"></div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<div class="checkbox">
								<label> <input type="checkbox" name="continue" value="1" <? echo (isset($_SESSION['continue_edit'])?'checked':''); ?>> продолжить редактирование </label>
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button class="btn btn-primary" type="submit">Сохранить</button> <button class="btn btn-small button_link" rel="<? echo BASE_PATH; ?>voting/list/" type="submit">Отменить</button>
						</div>
					</div>


				</form>
			</div>
		</div>
	</div>
</div>
