
									<div class="checkbox">
										 <label> <input type="checkbox" name="online" value="1"> показывать только онлайн</label> 
									</div> 


<div class="table-responsive">
			<table class="table table-intercoms table-hover">
				<thead>
					<tr>
						<th class="size-60"></th>						
						<th>Номер</th>
						<th>Адрес</th>
						<th>Клиенты</th>
						<th>Прошивка</th>						
						<th class="text-center">Статус XMPP</th>						
						<th class="text-center">Статус SIP</th>						
						<th class="size-80" class="text-center">Действия</th>
					</tr>
				</thead>
				<tbody>
				<? if($this->rows)
					foreach($this->rows as $row)
					{
						echo '<tr>
						<td class="size-60"><div class="form-checkbox"><input type="checkbox" name="id[]" class="id_field" value="'.$row['id'].'"> <span class="check"><i class="fa fa-check"></i></span></div></td>						
						<td><a title="редактировать" href="'.BASE_PATH.'intercoms/edit/'.$row['id'].'">'.$row['number'].'</a></td>						
						<td><a title="редактировать" href="'.BASE_PATH.'intercoms/edit/'.$row['id'].'">'.$row['addres'].'</a>';
						
						if($row['enter_all']==1)echo ' <br><span class="badge badge-bordered">Вход по любому ключу</span>';						echo '</td>
						<td>';
						if($row['clients']==0)echo $row['clients'];
						else echo '<a title="к списку клиентов" href="'.BASE_PATH.'clients/list/?filter=true&intercom='.$row['number'].'">'.$row['clients'].'</a>';
						echo '</td><td>'.$row['version'].'</td>						
						<td align=center>';
						if($row['xmpp_status']=='1')echo '<i title="статус подключения XMPP" class="icon-check icon-larger xmpp_status green-color"></i>';
						else echo '<i title="статус подключения XMPP" class="icon-check icon-larger xmpp_status red-color"></i>';
						echo '</td><td align=center>';						
						if($row['sip_status']=='1')echo '<i title="статус подключения" class="icon-check icon-larger sip_status green-color"></i>';
						else echo '<i title="статус подключения SIP" class="icon-cancel icon-larger sip_status red-color"></i>';
						echo '</td><td class="size-80">
							<div class="dropdown">
								<a href="#/" data-toggle="dropdown" class="more-link"><i class="icon-dot-3 ellipsis-icon"></i></a>
								<ul class="dropdown-menu dropdown-menu-right">
									<li><a href="'.BASE_PATH.'intercoms/edit/'.$row['id'].'">Редактировать</a></li>											
									<!--<li><a href="'.BASE_PATH.'intercoms/getconfig/'.$row['id'].'">Скачать cfg файл для домофона</a></li>-->
									<li><a href="'.BASE_PATH.'intercoms/log/'.$row['id'].'">Логи</a></li>											
									<!--<li><a href="'.BASE_PATH.'intercoms/config/'.$row['id'].'">Настройки</a></li>										-->	
									';												
									//<li><a href="'.BASE_PATH.'clients/block/'.$row['id'].'">Заблокировать</a></li>
							echo '<li><a href="'.BASE_PATH.'intercoms/delete/'.$row['id'].'" class="confirm" confirm="Вы уверены что хотите удалить домофон '.$row['fio'].'?">Удалить</a></li>																		
								</ul>
							</div>
						</td>
					</tr>';
					}
				?>						
				</tbody>
			</table>
			<div class="alert alert-info auto_off" style="display:none" role="alert"><strong>Внимание!</strong> Автоматическое обновление статусов домофонов остановлено, обновите страницу.</div>
		</div>
		

