<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>404 Страница не найдена</title>
<!-- Site favicon -->
<link rel='shortcut icon' type='image/x-icon' href='images/favicon.ico' />
<!-- /site favicon -->

<!-- Entypo font stylesheet -->
<link href="<? echo BASE_PATH; ?>css/entypo.css" rel="stylesheet">
<!-- /entypo font stylesheet -->

<!-- Font awesome stylesheet -->
<link href="<? echo BASE_PATH; ?>css/font-awesome.min.css" rel="stylesheet">
<!-- /font awesome stylesheet -->

<!-- Bootstrap stylesheet min version -->
<link href="<? echo BASE_PATH; ?>css/bootstrap.min.css" rel="stylesheet">
<!-- /bootstrap stylesheet min version -->

<!-- Mouldifi core stylesheet -->
<link href="<? echo BASE_PATH; ?>css/mouldifi-core.css" rel="stylesheet">
<!-- /mouldifi core stylesheet -->

<link href="<? echo BASE_PATH; ?>css/mouldifi-forms.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="<? echo BASE_PATH; ?>js/html5shiv.min.js"></script>
      <script src="<? echo BASE_PATH; ?>js/respond.min.js"></script>
<![endif]-->

</head>
<body class="page-error">
<div class="page-error-container">
	<div class="page-error-content">
		<div class="error-code">404</div>
		<h4 class="text-center title">Страница не найдена</h4>			
		<p class="text-center"><a href="<? echo BASE_PATH; ?>" class="btn btn-primary"> Вернуться на главную</a></p>
	</div>
</div>
<!--Load JQuery-->
<script src="<? echo BASE_PATH; ?>js/jquery.min.js"></script>
<script src="<? echo BASE_PATH; ?>js/bootstrap.min.js"></script>
</body>
</html>
