<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo $this->title() ?></title>

<!-- Entypo font stylesheet -->
<link href="<? echo CSS_PATH; ?>css/entypo.css" rel="stylesheet">
<!-- /entypo font stylesheet -->

<!-- Font awesome stylesheet -->
<link href="<? echo CSS_PATH; ?>css/font-awesome.min.css" rel="stylesheet">
<!-- /font awesome stylesheet -->

<!-- Bootstrap stylesheet min version -->
<link href="<? echo CSS_PATH; ?>css/bootstrap.min.css" rel="stylesheet">
<!-- /bootstrap stylesheet min version -->

<!-- Mouldifi core stylesheet -->
<link href="<? echo CSS_PATH; ?>css/mouldifi-core.css" rel="stylesheet">
<!-- /mouldifi core stylesheet -->

<link href="<? echo CSS_PATH; ?>css/mouldifi-forms.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="<? echo CSS_PATH; ?>js/html5shiv.min.js"></script>
      <script src="<? echo CSS_PATH; ?>js/respond.min.js"></script>
<![endif]-->


</head>
<body class="login-page">
<div class="login-container">
	<div class="login-branding">
		<a href="index.html"><img src="<? echo CSS_PATH; ?>/images/feelindomophone-logo.svg" alt="Feelin' domofon" title="Feelin' domofon"></a>
	</div>
	<div class="login-content">
		<h2>Авторизация</h2>
		<?php 
			$mess= $this->message();
			if($mess) echo '<div class="alert alert-warning" role="alert">'.$mess.'</div>';
		?>
		 <?php echo $this->content ?>		
	</div>
</div>
<!--Load JQuery-->
<script src="<? echo CSS_PATH; ?>js/jquery.min.js"></script>
<script src="<? echo CSS_PATH; ?>js/bootstrap.min.js"></script>
</body>
</html>
