<?
#print_r($_SESSION);
#echo "!!!";
#print_r($this->rows);
?>
                <div class="table-responsive">
                        <table class="table table-users table-hover">
                                <thead>
                                        <tr>
                                                <th class="size-60"></th>
                                                <th>ФИО</th>
                                                <th>Логин</th>
                                                <th>Права</th>
                                                <th>Управляющая компания</th>
                                                <th>Комент</th>
                                                <th>Контакты</th>
                                                <th class="text-center">Статус</th>
                                                <th class="size-80" class="text-center">Действия</th>
                                        </tr>
                                </thead>
                                <tbody>
                                <? if($this->rows)
                                        foreach($this->rows as $row)
                                        {
                                                echo '<tr>
                                                <td class="size-60"><div class="form-checkbox"><input type="checkbox" name="id[]" class="id_field" value="'.$row['id'].'"> <span class="check"><i class="fa fa-check"></i></span></div></td>
                                                <td><a href="'.BASE_PATH.'clients/edit/'.$row['id'].'">'.$row['name'].'</a></td>
                                                <td>'.(empty($row['phone'])?'':'+7 '.$row['phone']).'</td>
                                                <td>'.$row['city'].'</td>
                                                <td>'.$row['addres'].'</td>
                                                <td>'.$row['flat'].'</td>
                                                <td>'.$row['intercom'].'</td>
                                                <td class="text-center">';
                                                foreach($row['services'] as $intercom)
                                                {
                                                        foreach($intercom as $name=>$value)
                                                                if($value==1)echo ' <span class="badge badge-bordered">'.$name.'</span>';
                                                        echo '<br>';
                                                }
                                                echo '</td>
                                                <td align=center>';
                                                //if($row['act']=='1')
                                                if($row['is_debt']=='0')
                                                        echo '<a title="заблокировать" href="'.BASE_PATH.'clients/block/'.$row['id'].'"><i class="icon-check icon-larger green-color"></i></a>';
                                                else echo '<a  title="разблокировать" href="'.BASE_PATH.'clients/activate/'.$row['id'].'"><i class="icon-check icon-larger red-color"></i></a>';
                                                echo '</td><td class="size-80">
                                                        <div class="dropdown">
                                                                <a href="#/" data-toggle="dropdown" class="more-link"><i class="icon-dot-3 ellipsis-icon"></i></a>
                                                                <ul class="dropdown-menu dropdown-menu-right">
                                                                <li><a href="'.BASE_PATH.'clients/edit/'.$row['id'].'">Редактировать</a></li>
                                                                        ';
                                                //if($row['act']=='1')
                                                if($row['is_debt']=='0')
                                                        echo '<li><a href="'.BASE_PATH.'clients/block/'.$row['id'].'">Заблокировать</a></li>';
                                                else echo '<li><a href="'.BASE_PATH.'clients/activate/'.$row['id'].'">Разблокировать</a></li>';
                                                        echo '<li><a href="'.BASE_PATH.'clients/reset/'.$row['id'].'" class="confirm" confirm="Вы уверены что хотите сбросить пароль клиента '.$row['fio'].'?">Сбросить пароль</a></li>
                                                                  <li><a href="'.BASE_PATH.'notify/add/'.$row['id'].'">Отправить сообщение</a></li>
                                                                  <li><a href="'.BASE_PATH.'clients/delete/'.$row['id'].'" class="confirm" confirm="Вы уверены что хотите удалить клиента '.$row['fio'].'?">Удалить</a></li>
                                                                </ul>
                                                        </div>
                                                </td>
                                        </tr>';
                                        }
                                ?>
                                </tbody>
                        </table>